### ISSUE TITLE
Startup Projeto

### ISSUE THREAD

**Issue by ricardojmserra** [ricardojmserra/Wimari#5]
# Descrição
Começar um Projeto vazio que conecte ao Azure e dar deploy de uma webapp vazia

# Tasks
- [ ] Começar um projeto com SpringBoot
- [ ] Criar conta estudante na Azure
- [ ] Configuração para testes locais
- [ ] Configuração para deploy na Azure
